# Generated by Django 4.0.3 on 2022-05-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_officer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
