# Generated by Django 4.0.3 on 2022-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
